# Generated by Django 6.0.7 on 2026-07-14 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaoDeObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maodeobras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mão de obra',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='PecaEmFalta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('quantidade_desejada', models.PositiveIntegerField(default=1)),
                ('comprado', models.BooleanField(default=False)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='falta_pecas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Peças em falta',
                'ordering': ['comprado', '-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mecanico', 'Mecânico'), ('vendedor', 'Vendedor')], max_length=10)),
                ('aprovado', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
